apiVersion: v1
kind: Template
metadata:
  name: collab-by-code-api-template
  annotations:
    description: "RHCollab By Code Event API"
    iconClass: "icon-nodejs"
    tags: "nodejs"
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: collab-by-code-api
      annotations: {}
    data:
      db.path: "/opt/app-root/src/dist"
      db.name: "eventdb.json"
      uploads.path: "/opt/app-root/src/dist/uploads"
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app: collab-by-code-api
      name: collab-by-code-api
    spec:
      ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: collab-by-code-api
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations: {}
      labels:
        app: collab-by-code-api
      name: collab-by-code-api
    spec:
      replicas: 1
      selector:
        deploymentconfig: collab-by-code-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: collab-by-code-api
            deploymentconfig: collab-by-code-api
        spec:
          containers:
            - env:
                - name: DB_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: collab-by-code-api
                      key: db.path
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: collab-by-code-api
                      key: db.name
                - name: UPLOADS_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: collab-by-code-api
                      key: uploads.path
              image: "collab-by-code-api:latest"
              imagePullPolicy: IfNotPresent
              name: collab-by-code-api
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
        triggers:
          - imageChangeParams:
              automatic: true
              containerNames:
                - collab-by-code-api
              from:
                kind: ImageStreamTag
                name: "collab-by-code-api:latest"
                namespace: myproject
            type: ImageChange
          - type: ConfigChange
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations: {}
      labels:
        app: collab-by-code-api
      name: collab-by-code-api
    spec:
      ouput:
        to:
          kind: ImageStreamTag
          name: "collab-by-code-api:latest"
      source:
        git:
          ref: master
          uri: "https://github.com/kameshsampath/collab-by-code-api.git"
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "nodejs:8"
            namespace: openshift
        type: Source
      triggers:
        - generic:
            secret: 20d85e46ec8875fe
          type: Generic
        - github:
            secret: 1229ed9ba5fe5002
          type: GitHub
        - type: ImageChange
        - type: ConfigChange
